on: push
name: ðŸš€ SG Staging Deployment
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy - SG Staging
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@master
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: vm-bobby.cloudhfc.com
        username: bipadmin@localnearmedirectory.com
        port: 21
        password: ${{ secrets.BIP_FTP_PASS }}
        server-dir: /domains/localnearmedirectory.com/public_html/wp-content/plugins/bip-network-kit/
        exclude: |
            readme.txt
            utils.js
            todo.txt
            scoper.inc.php
            webpack.*.js
            **/Gruntfile.js
            **/.*
            **/.git/**
            **/.github/**